export const TYPES = {
	Application: Symbol.for('Application'),
	ILogger: Symbol.for('ILogger'),
	IUserController: Symbol.for('IUserController'),
	IUserService: Symbol.for('IUserService'),
	IExceptionFilter: Symbol.for('IExceptionFilter'),
	IConfigService: Symbol.for('IConfigService'),
	PostgresqlService: Symbol.for('PostgresqlService'),
	IUsersRepository: Symbol.for('IUsersRepository'),
	CollectionController: Symbol.for('CollectionController'),
	CollectionService: Symbol.for('CollectionService'),
	CollectionRepository: Symbol.for('CollectionRepository'),
	ImageController: Symbol.for('ImageController'),
	ImageService: Symbol.for('ImageService'),
	ImageRepository: Symbol.for('ImageRepository'),
	PriceController: Symbol.for('PriceController'),
	PriceRepository: Symbol.for('PriceRepository'),
	PriceService: Symbol.for('PriceService'),
	StockController: Symbol.for('StockController'),
	StockService: Symbol.for('StockService'),
	StockRepository: Symbol.for('StockRepository'),
};
